/**
 * Change Order Formatter
 *
 * Formats change orders as markdown-compatible text for clipboard
 * and text file exports.
 *
 * @module ChangeOrderFormatter
 */

/**
 * Format change order as markdown-compatible text
 *
 * @param {ChangeOrder} changeOrder - Change order to format
 * @returns {string} Formatted text
 */
export function formatAsText(changeOrder) {
  const lines = [];

  // Header
  lines.push('# CHANGE ORDER');
  lines.push('');
  lines.push(`**Order Number:** ${changeOrder.changeOrderNumber}`);
  lines.push(`**Date:** ${changeOrder.dateCreated || new Date().toLocaleDateString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Client Information
  lines.push('## Client Information');
  lines.push('');
  lines.push(`**Name:** ${changeOrder.clientName}`);
  lines.push(`**Email:** ${changeOrder.clientEmail}`);
  lines.push('');

  // Freelancer Information
  lines.push('## Freelancer');
  lines.push('');
  lines.push(`**Name:** ${changeOrder.freelancerName}`);
  lines.push('');

  // Original Scope
  lines.push('## Original Scope');
  lines.push('');
  lines.push(changeOrder.originalScope || 'Not specified');
  lines.push('');

  // Requested Changes
  lines.push('## Requested Changes');
  lines.push('');
  if (Array.isArray(changeOrder.requestedChanges) && changeOrder.requestedChanges.length > 0) {
    changeOrder.requestedChanges.forEach((change, index) => {
      lines.push(`${index + 1}. ${change}`);
    });
  } else {
    lines.push('No changes specified');
  }
  lines.push('');

  // Cost Estimate
  lines.push('## Cost Estimate');
  lines.push('');
  lines.push(changeOrder.costEstimate || 'TBD');
  lines.push('');

  // Revised Timeline
  lines.push('## Revised Timeline');
  lines.push('');
  lines.push(changeOrder.revisedTimeline || 'To be determined');
  lines.push('');

  // Payment Terms
  lines.push('## Payment Terms');
  lines.push('');
  lines.push(changeOrder.paymentTerms || 'Net 30');
  lines.push('');

  // Additional Notes (if present)
  if (changeOrder.additionalNotes && changeOrder.additionalNotes !== 'No additional notes') {
    lines.push('## Additional Notes');
    lines.push('');
    lines.push(changeOrder.additionalNotes);
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by ScopeShield on ${new Date().toLocaleString()}*`);

  return lines.join('\n');
}

/**
 * Create a sanitized filename for a change order text export.
 *
 * @param {ChangeOrder} changeOrder - Object containing at least `changeOrderNumber` and optionally `clientName`.
 * @returns {string} Filename in the format `ChangeOrder_<orderNum>_<clientName>_<YYYY-MM-DD>.txt`, where `orderNum` has any leading `#` removed and `clientName` is sanitized to alphanumeric/underscore characters (defaults to `Client` if missing).
 */
export function generateTextFilename(changeOrder) {
  const date = new Date().toISOString().split('T')[0];
  const clientName = (changeOrder.clientName || 'Client').replace(/[^a-zA-Z0-9]/g, '_');
  const orderNum = changeOrder.changeOrderNumber.replace('#', '');

  return `ChangeOrder_${orderNum}_${clientName}_${date}.txt`;
}