/**
 * Fallback Template Tests
 * Tests for graceful degradation when template processing fails
 */

import { describe, it, expect } from 'vitest';
import {
  generateFallbackChangeOrder,
  generateMinimalFallback,
  renderFallback
} from '../../../src/lib/change-order/fallbackTemplate.js';

describe('fallbackTemplate', () => {
  describe('generateFallbackChangeOrder', () => {
    it('should generate fallback with all variables', () => {
      const variables = {
        clientName: 'Acme Corp',
        freelancerName: 'Jane Doe',
        date: '2025-11-19',
        changeRequestSummary: 'Additional features requested',
        detectedChanges: ['New payment gateway', 'Extra reporting dashboard'],
        costEstimate: '$2,500.00',
        revisedTimeline: '2 additional weeks',
        paymentTerms: '50% upfront, 50% on delivery',
        originalScope: 'E-commerce website',
        additionalNotes: 'Client approved on call'
      };

      const result = generateFallbackChangeOrder(variables);

      expect(result).toContain('CHANGE ORDER REQUEST');
      expect(result).toContain('Acme Corp');
      expect(result).toContain('Jane Doe');
      expect(result).toContain('2025-11-19');
      expect(result).toContain('Additional features requested');
      expect(result).toContain('1. New payment gateway');
      expect(result).toContain('2. Extra reporting dashboard');
      expect(result).toContain('$2,500.00');
      expect(result).toContain('2 additional weeks');
      expect(result).toContain('50% upfront, 50% on delivery');
      expect(result).toContain('E-commerce website');
      expect(result).toContain('Client approved on call');
      expect(result).toContain('Generated by ScopeShield');
    });

    it('should use defaults for missing variables', () => {
      const variables = {};

      const result = generateFallbackChangeOrder(variables);

      expect(result).toContain('Client');
      expect(result).toContain('Freelancer');
      expect(result).toContain('Scope change detected');
      expect(result).toContain('$0.00');
      expect(result).toContain('To be determined');
    });

    it('should handle single detected change', () => {
      const variables = {
        detectedChanges: ['One change only']
      };

      const result = generateFallbackChangeOrder(variables);

      expect(result).toContain('1. One change only');
      expect(result).not.toContain('2.');
    });

    it('should handle empty detected changes array', () => {
      const variables = {
        detectedChanges: []
      };

      const result = generateFallbackChangeOrder(variables);

      expect(result).toContain('1. Scope change detected');
    });

    it('should handle non-array detected changes', () => {
      const variables = {
        detectedChanges: 'not an array'
      };

      const result = generateFallbackChangeOrder(variables);

      expect(result).toContain('1. Scope change detected');
    });
  });

  describe('generateMinimalFallback', () => {
    it('should generate minimal fallback template', () => {
      const result = generateMinimalFallback();

      expect(result).toContain('CHANGE ORDER REQUEST');
      expect(result).toContain('Date:');
      expect(result).toContain('scope change has been detected');
      expect(result).toContain('Cost estimate');
      expect(result).toContain('Revised timeline');
      expect(result).toContain('Payment terms');
      expect(result).toContain('Generated by ScopeShield');
    });

    it('should include current date', () => {
      const result = generateMinimalFallback();
      const today = new Date().toISOString().split('T')[0];

      expect(result).toContain(today);
    });
  });

  describe('renderFallback', () => {
    it('should use full fallback when variables provided', () => {
      const variables = {
        clientName: 'Test Client',
        detectedChanges: ['Change 1']
      };

      const result = renderFallback(variables);

      expect(result).toContain('Test Client');
      expect(result).toContain('Change 1');
    });

    it('should use minimal fallback when no variables provided', () => {
      const result = renderFallback(null);

      expect(result).toContain('scope change has been detected');
      expect(result).not.toContain('Client:');
    });

    it('should use minimal fallback for non-object variables', () => {
      const result = renderFallback('not an object');

      expect(result).toContain('scope change has been detected');
    });

    it('should use full fallback for empty object', () => {
      const result = renderFallback({});

      expect(result).toContain('Client:');
      expect(result).toContain('Freelancer:');
    });
  });
});
