/**
 * Fallback Template Generator
 *
 * Provides simple plain-text template rendering when primary template
 * processing fails due to malformed templates, parsing errors, or other issues.
 *
 * Part of Phase 8 (T370-T374): Template Robustness
 *
 * @module fallbackTemplate
 */

/**
 * Create a plain-text change order document from provided template values.
 *
 * Missing fields are replaced with sensible defaults. If `detectedChanges` is a non-empty array,
 * each entry is rendered as a numbered line; otherwise a single default line is used.
 *
 * @param {Object} variables - Template values for the change order.
 * @param {string} [variables.clientName='Client'] - Client display name.
 * @param {string} [variables.freelancerName='Freelancer'] - Freelancer display name.
 * @param {string} [variables.date] - ISO date (YYYY-MM-DD); defaults to today's date.
 * @param {string} [variables.changeRequestSummary='Scope change detected'] - Short summary of the requested changes.
 * @param {string[]} [variables.detectedChanges=[]] - List of detected change descriptions; rendered as numbered items.
 * @param {string} [variables.costEstimate='$0.00'] - Total additional cost estimate.
 * @param {string} [variables.revisedTimeline='To be determined'] - Revised timeline description.
 * @param {string} [variables.paymentTerms='50% upfront, 50% on completion'] - Payment terms text.
 * @param {string} [variables.originalScope='Original project scope'] - Original project scope description.
 * @param {string} [variables.additionalNotes=''] - Any additional notes to include.
 * @returns {string} The formatted plain-text change order document.
 */
export function generateFallbackChangeOrder(variables) {
  const {
    clientName = 'Client',
    freelancerName = 'Freelancer',
    date = new Date().toISOString().split('T')[0],
    changeRequestSummary = 'Scope change detected',
    detectedChanges = [],
    costEstimate = '$0.00',
    revisedTimeline = 'To be determined',
    paymentTerms = '50% upfront, 50% on completion',
    originalScope = 'Original project scope',
    additionalNotes = ''
  } = variables;

  // Build change list
  const changesList = Array.isArray(detectedChanges) && detectedChanges.length > 0
    ? detectedChanges.map((change, index) => `${index + 1}. ${change}`).join('\n')
    : '1. Scope change detected';

  // Format plain-text document
  return `
CHANGE ORDER REQUEST

Date: ${date}
Client: ${clientName}
Freelancer: ${freelancerName}

---

SUMMARY OF REQUESTED CHANGES

${changeRequestSummary}

DETECTED CHANGES:

${changesList}

---

ORIGINAL SCOPE

${originalScope}

---

COST ESTIMATE

Total Additional Cost: ${costEstimate}

REVISED TIMELINE

${revisedTimeline}

PAYMENT TERMS

${paymentTerms}

---

ADDITIONAL NOTES

${additionalNotes}

---

Generated by ScopeShield
  `.trim();
}

/**
 * Produce a minimal plain-text change order used when no template variables are available.
 *
 * @returns {string} A compact, human-readable change order template containing the date, a notice of scope change, and prompts for a cost estimate, revised timeline, and payment terms.
 */
export function generateMinimalFallback() {
  return `
CHANGE ORDER REQUEST

Date: ${new Date().toISOString().split('T')[0]}

A scope change has been detected.

Please review the requested changes and provide:
- Cost estimate for additional work
- Revised timeline
- Payment terms

Generated by ScopeShield
  `.trim();
}

/**
 * Selects and returns the appropriate plain-text fallback change order based on provided variables.
 * @param {Object} variables - Template values; when an object is provided, a detailed fallback is generated using its fields. If not an object, a minimal fallback is returned.
 * @returns {string} A plain-text change order: the detailed fallback when `variables` is an object, otherwise the minimal fallback.
 */
export function renderFallback(variables) {
  // If we have minimal data, use full fallback with defaults
  if (variables && typeof variables === 'object') {
    return generateFallbackChangeOrder(variables);
  }

  // Last resort: minimal fallback
  return generateMinimalFallback();
}