/**
 * Fallback Template Generator
 *
 * Provides simple plain-text template rendering when primary template
 * processing fails due to malformed templates, parsing errors, or other issues.
 *
 * Part of Phase 8 (T370-T374): Template Robustness
 *
 * @module fallbackTemplate
 */

/**
 * Generate fallback change order document from variables
 * Uses plain text formatting without complex template logic
 * @param {Object} variables - Template variables
 * @returns {string} Plain-text formatted change order
 */
export function generateFallbackChangeOrder(variables) {
  const {
    clientName = 'Client',
    freelancerName = 'Freelancer',
    date = new Date().toISOString().split('T')[0],
    changeRequestSummary = 'Scope change detected',
    detectedChanges = [],
    costEstimate = '$0.00',
    revisedTimeline = 'To be determined',
    paymentTerms = '50% upfront, 50% on completion',
    originalScope = 'Original project scope',
    additionalNotes = ''
  } = variables;

  // Build change list
  const changesList = Array.isArray(detectedChanges) && detectedChanges.length > 0
    ? detectedChanges.map((change, index) => `${index + 1}. ${change}`).join('\n')
    : '1. Scope change detected';

  // Format plain-text document
  return `
CHANGE ORDER REQUEST

Date: ${date}
Client: ${clientName}
Freelancer: ${freelancerName}

---

SUMMARY OF REQUESTED CHANGES

${changeRequestSummary}

DETECTED CHANGES:

${changesList}

---

ORIGINAL SCOPE

${originalScope}

---

COST ESTIMATE

Total Additional Cost: ${costEstimate}

REVISED TIMELINE

${revisedTimeline}

PAYMENT TERMS

${paymentTerms}

---

ADDITIONAL NOTES

${additionalNotes}

---

Generated by ScopeShield
  `.trim();
}

/**
 * Generate minimal fallback when no variables available
 * Used as last resort when template rendering and variable extraction both fail
 * @returns {string} Minimal change order template
 */
export function generateMinimalFallback() {
  return `
CHANGE ORDER REQUEST

Date: ${new Date().toISOString().split('T')[0]}

A scope change has been detected.

Please review the requested changes and provide:
- Cost estimate for additional work
- Revised timeline
- Payment terms

Generated by ScopeShield
  `.trim();
}

/**
 * Determine which fallback to use based on available data
 * @param {Object} variables - Available template variables
 * @returns {string} Appropriate fallback document
 */
export function renderFallback(variables) {
  // If we have minimal data, use full fallback with defaults
  if (variables && typeof variables === 'object') {
    return generateFallbackChangeOrder(variables);
  }

  // Last resort: minimal fallback
  return generateMinimalFallback();
}
